

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_24 = Integer(24); _sage_const_1 = Integer(1)
from sage.repl.ipython_kernel.kernel import SageKernel
from sage.repl.interpreter import sage_prompt_toolkit

sage_prompt_toolkit.init(auto_show=True)
SageKernel.default_kernel().do_execute("""show._pretty_printers_enabled = True""")

show()
var('x y p q')
eq1 = p+q==_sage_const_9 
eq2 = q*y+p*x==-_sage_const_6 
eq3 = q*y**_sage_const_2 +p*x**_sage_const_2 ==_sage_const_24 
solve([eq1,eq2,eq3,p==_sage_const_1 ],p,q,x,y)





